### ISSUE TITLE
Consider normalizing yaml files using yamllint

### ISSUE THREAD

**Issue by xhernandez** [samba-in-kubernetes/sit-environment#10]
We use many yaml files and yamllint shows some concerns. Should we fix them ?

Currently this is what we have:

    57  warning  missing document start "---" (document-start)
    48  error    too many spaces inside braces (braces)
    41  error    line too long (line-length)
    36  warning  truthy value should be one of [false, true] (truthy)
     7  error    too many blank lines (empty-lines)
     6  error    wrong indentation: (indentation)
     5  warning  missing starting space in comment (comments)
     1  error    no new line character at the end of file (new-line-at-end-of-file)

**Comment by anoopcs9** [comment]
Given the fact that we use lot of YAML files for ansible automation we could bring in the support for `yamllint` check(similar to https://github.com/samba-in-kubernetes/samba-container/pull/132) to ensure we cope with bare minimum(and not too complex) standards.

Even otherwise I am all for fixing the current issues in one shot.

What are your thoughts? @spuiuk @obnoxxx @phlogistonjohn

**Comment by xhernandez** [comment]
Considering that this repo has many yaml files, I would say that we should enable rules that make all yaml consistent. From the list I provided in the first comment, I think we could relax (but not disable) 'truthy', 'line-length' and 'braces' rules. The remaining rules should be kept to make all yaml similar. I would also consider choosing between single or double quotes for strings when necessary to use a common criteria in all files.

What do you think ?

**Comment by xhernandez** [comment]
@phlogistonjohn @anoopcs9 @spuiuk What do you think about these changes from the default yamllint config ?

```diff
   anchors:
     forbid-undeclared-aliases: true
-    forbid-duplicated-anchors: false
-    forbid-unused-anchors: false
+    forbid-duplicated-anchors: true
+    forbid-unused-anchors: true
     level: error
```

I don't think we use anchors anywhere, but if we use them, a duplicate or unused anchor is most probably a symptom of a typo, so better point to them.
<hr />

```diff 
   braces:
     forbid: false
     min-spaces-inside: 0
-    max-spaces-inside: 0
-    min-spaces-inside-empty: -1
-    max-spaces-inside-empty: -1
+    max-spaces-inside: 1
+    min-spaces-inside-empty: 0
+    max-spaces-inside-empty: 1
     level: error
```
I think that a space inside the braces is frequently used. I apply the same criteria for empty braces.
<hr />

```diff
   brackets:
     forbid: false
     min-spaces-inside: 0
-    max-spaces-inside: 0
-    min-spaces-inside-empty: -1
-    max-spaces-inside-empty: -1
+    max-spaces-inside: 1
+    min-spaces-inside-empty: 0
+    max-spaces-inside-empty: 1
     level: error
```
This is equivalent to the rationale for braces.
<hr />

```diff
-  document-end: disable
+  document-end:
+    present: false
+    level: error
```
We haven't used the document end mark (`...`) anywhere, so we can enforce to never use it to ensure consistency
<hr />

```diff
   document-start:
     present: true
-    level: warning
+    level: error
```
To make all yaml documents consistent, I would enforce starting all of them with `---`.
<hr />

```diff
   empty-lines:
-    max: 2
+    max: 1
     max-start: 0
     max-end: 0
     level: error
```
I think just one space to separate things should be enough.
<hr />

```diff
-  empty-values: disable
+  empty-values:
+    forbid-in-block-mappings: true
+    forbid-in-flow-mappings: true
+    level: error
```
An empty value is rarely used, but on the other hand could indicate an indentation mistake, so I think it's better to forbid empty values. If an empty value is really required, `{}`, `[]` or `null` can be used.
<hr />

```diff
-  float-values: disable
+  float-values:
+    forbid-inf: true
+    forbid-nan: true
+    forbid-scientific-notation: false
+    require-numeral-before-decimal: false
+    level: error
```
In case we ever need to use float values, infinite and NaN will hardly be valid values (at least in this repo), so better to catch them and throw an error.
<hr />

```diff
   indentation:
-    spaces: consistent
+    spaces: 2
     indent-sequences: true
     check-multi-line-strings: false
     level: error
```
To make force consistency between all yaml documents just define indentation as 2 spaces, instead of requiring only internal consistency.
<hr />

```diff
   line-length:
-    max: 80
+    max: 100
     allow-non-breakable-words: true
     allow-non-breakable-inline-mappings: false
-    level: error
+    level: warning
```
Too long lines are bad, but 80 might be too short in some cases. I think increasing the limit to 100 (or even 120) could be fine, but in any case I would just warn about longer lines but not cause an error.
<hr />

```diff
   new-lines:
     type: unix
-    level: error
+    level: warning
```
Probably it's not a big issue if the files get edited from Windows and the line endings are '\r\n', though I'm ok to leave this as an error.
<hr />

```diff
   truthy:
-    allowed-values: ['true', 'false']
-    check-keys: true
+    allowed-values: ['true', 'false', 'yes', 'no']
+    check-keys: false
     level: warning
```
In ansible we use yes/no with some frequency. We should allow them to be used as booleans. Also, it doesn't make sense to check for boolean values in keys, since they are always treated as strings.

**Comment by anoopcs9** [comment]
@xhernandez Please feel free to propose a PR according to your suggested set of rules.

**Comment by xhernandez** [comment]
I created #12. I did some changes from the initially proposed configuration to minimize problems with some constructs.
