### ISSUE TITLE
Possible inclusion of `ignore system acls = yes` option for vfs_acl_xattr

### ISSUE THREAD

**Issue by anoopcs9** [samba-in-kubernetes/sit-environment#81]
In a recent investigation related to failure with `smb2.session.reauth4` smbtorture test case it was revealed that the `ignore system acls = yes` optional parameter for _vfs_acl_xattr_ module could be a sensible configuration in general to better match NT ACLs provided the lossy translation approach otherwise used. More details to follow..

**Comment by anoopcs9** [comment]
_smb2.session.reauth4_ used to fail with `NT_STATUS_ACCESS_DENIED` as follows:

> test: samba3.smb2.session.reauth4
> time: 2024-02-05 02:25:52.032856Z
> time: 2024-02-05 02:25:52.052116Z
> failure: samba3.smb2.session.reauth4 [
> Exception: ../../source4/torture/smb2/session.c:603: status was NT_STATUS_ACCESS_DENIED, expected NT_STATUS_OK: smb2_setinfo_file failed
> ]

Test case itself tries to re-authenticate anonymously and a subsequent attempt to modify ACLs for a file created previously by another user fails. This is expected to work but Samba's attempt to map such ACL modifications to POSIX world is lossy in nature resulting in `EPERM`. With the help of _vfs_acl_xattr_ module we could avoid such lossy mapping thereby storing the ACLs directly via xattr on the file. `ignore system acls = yes` is the optional parameter in question here.

**Comment by xhernandez** [comment]
I understand the problem, but is "ignore system acls" the right solution ?

If I'm not wrong, it makes all ACL checks to rely on the NT_ACL xattr (samba specific xattr) and use "permissive" posix ACLs. In this case, anything else trying to access the same backend filesystem (for example if we want to access it also from NFS) will surely have permission issues.

In any case, I think it'll be a good option to make it configurable in sit-environment.

**Comment by anoopcs9** [comment]
> I understand the problem, but is "ignore system acls" the right solution ?

While debugging the failure I figured out that this option can solve the problem post which I had a discussion with upstream. It turned out that this particular situation/test case can only work with the help of additional `ignore system acls` parameter.

> If I'm not wrong, it makes all ACL checks to rely on the NT_ACL xattr (samba specific xattr) and use "permissive" posix ACLs. In this case, anything else trying to access the same backend filesystem (for example if we want to access it also from NFS) will surely have permission issues.

Obviously, this is already mentioned in man [vfs_acl_xattr(8)](https://www.samba.org/samba/docs/current/man-html/vfs_acl_xattr.8.html) since its inception I guess.

> In any case, I think it'll be a good option to make it configurable in sit-environment.

Probably. I can think of places where we can fit such an option. Do you have any idea? Should it be a global option?

**Comment by xhernandez** [comment]
For sit-environment it should be irrelevant, but I just wanted to raise the flag about multiprotocol access.

For now I would put these samba configuration options inside _playbooks/ansible/cluster-<backend>.yml_. In _samba_shares_ we can add an _options_ key to include key-value pairs for each option to modify in that share. I don't think this is the best solution, but it's the easier one right now. I'm thinking to move several things from these _cluster-<backend>.yml_ files to other places to reduce duplication of settings, but I would do that in a future change.

A generic approach could be:

```yaml
samba_shares:
  - cluster_volume: samba
    share_name: share
    options:
      "samba option name": "value"
```
